name: Release

on:
  release:
    types: [released]

jobs:
  get_app_version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - id: app_version
        name: Export version
        run: echo "APP_VERSION=$(head -n 5 Cargo.toml | grep version | cut -d '"' -f2)" >> $GITHUB_OUTPUT
    outputs:
      app_version: ${{ steps.app_version.outputs.APP_VERSION }}

  release_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/s3rius/kuo:latest,ghcr.io/s3rius/kuo:${{ github.ref_name }}

  upload_helm:
    runs-on: ubuntu-latest
    needs: [get_app_version, release_image]
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Build CRDs
        run: cargo run --bin kuo-crds helm/templates/files/crds.yaml
      - name: Push Helm chart to OCI compatible registry (Github)
        uses: bsord/helm-push@master
        with:
          useOCIRegistry: true
          registry-url:  oci://ghcr.io/s3rius/kuo
          chart-folder: helm
          username: ${{ github.actor}}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          appVersion: ${{ needs.get_app_version.outputs.app_version }}
      - name: Upload CRDs to the release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: helm/templates/files/crds.yaml
          asset_name: crds.yaml
          tag: ${{ github.ref }}
          overwrite: true
