name: Release

on:
  release:
    types: [released]

jobs:
  release_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/s3rius/kuo:latest,ghcr.io/s3rius/kuo:${{ github.ref_name }}

  upload_helm:
    runs-on: ubuntu-latest
    needs: [release_image]
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - uses: azure/setup-helm@v4.2.0
        with:
          version: latest
      - name: Build CRDs
        run: cargo run --bin kuo-crds helm/crds/crds.yaml
      - name: Build Helm chart
        run: |
          helm package --app-version "${{ github.ref_name }}" --dependency-update ./helm
          helm show chart *.tgz
          helm registry login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          helm push *.tgz oci://ghcr.io/s3rius/charts
        env:
          HELM_EXPERIMENTAL_OCI: 1
      - name: Upload CRDs to the release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: helm/crds/crds.yaml
          asset_name: crds.yaml
          tag: ${{ github.ref }}
          overwrite: true
