name: Release
on:
    push:
        branches:
            - master
    # release:
    #     types:
    #         - released
jobs:
    release:
        strategy:
          matrix:
            platform:
                - linux/amd64
                - linux/arm/v6
                - linux/arm/v7
                - linux/arm64
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Docker
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  platforms: ${{ matrix.platform }}
                  push: true
                  tags: ghcr.io/s3rius/kuo:latest

